## 日志收集服务 Runner panic 导致计量出错


### 看为什么会panic

DomainGetter 类型是一个interface，而 NewDomaingClient 返回 *DomainClient struct 指针，将 *DomainClient nil 赋值给 DomainGetter interface，最终使用 DomainGetter != nil 则执行逻辑，导致空指针panic

```go
type DomainClient struct {}
type DomainGetter interface {}

func GetDomain(ctx context.Context, req *pb.GetDomainReq) (*GetDomainResp, error) {
    var c DomainGetter
	c = NewDomainClient()
	if c == nil {
		return nil, errors.New("domainGetter is nil")
	}
	return c.DomainGetter.GetDomain(ctx, req)
}

func NewDomainClient() *DomainClient {
	return nil
}
```

### 为什么是连续panic

外层是一个死循环并且做了recover()，也就解释了为什么连续panic，panic之后被recover，进入下一次for循环


### 为什么是规律10分钟一次panic

Runner 每次读取“一批数据”再进行后续的处理，一批数据的定义的最大行数、最大数据量、最大读取时间满足其一，这里最大读取时间为10分钟一次，每次读到一批数据进行处理时发生panic，也就表现为10分钟panic一次


### 为什么会丢数据？以及丢了哪些数据

理论上Runner重新加载的过程中优先从meta记录的位置继续读数据，没有meta的情况下才会根据read_from配置选择开始读的位置（从头或者从尾读）
meta 信息保存在本地，而问题发生时meta信息是存在的，且记录位置正确


* 猜测1: panic后不断读取下一批数据，老的文件读完之后标记为 done，而已经标记 done 的文件不会被重复读取

如果是这种场景，那丢失的数据应该是第一次panic发生时的正在读取的文件f1，到问题修复时正在读取的文件fn，不包含f1和fn，f1 重新初始化的时候从meta读取，只有在选取下一个文件的时候才会判断是否已经标记为 done，fn还没有读完所以不会标记为done

对比问题现场标记为done的文件，并没有此现象，推翻猜测

* 猜测2: Runner 重新加载实际是先Remove(Stop)再Add，在Remove过程中先将Runner状态置为stopped，从而触发一次meta同步(在run过程中发现Runner状态已经stoped则会同步meta信息)，导致将最新的读取游标同步到了meta

经过测试环境模拟测试和代码分析，验证了这种猜测 (在不断panic过程中不会更新meta信息，只有重新加载的时候更新meta信息为最新读取位置)
tips: 如果问题发生时直接kill进程，那么meta信息不会破坏，下次启动会从meta记录的位置继续读取，不会丢数据
